#!/bin/bash
# postinst script for geonode
#
# see: dh_installdeb(1)

set -e

# summary of how this script can be called:
#	* <postinst> `configure' <most-recently-configured-version>
#	* <old-postinst> `abort-upgrade' <new version>
#	* <conflictor's-postinst> `abort-remove' `in-favour' <package>
#	  <new-version>
#	* <postinst> `abort-remove'
#	* <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#	  <failed-install-package> <version> `removing'
#	  <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package

case "$1" in
    configure)
         if [ "$2" = "1.1+RC2" ]
         then
             # Migrate old varchar fields to TEXT
             su - postgres -c 'psql geonode' <<EOF
ALTER TABLE maps_maplayer 
    ALTER COLUMN layer_params TYPE text,
    ALTER COLUMN source_params TYPE text;
EOF
         fi
	 
         if [ "$2" = "" ]
         then
		 /usr/share/geonode/install.sh -s once /usr/share/geonode/config-post.sh
         fi

# ALWAYS run the postinstall tasks
	 /usr/share/geonode/install.sh -s post /usr/share/geonode/config-post.sh

         if [ "$2" = "" ]
         then
		 /usr/share/geonode/install.sh -s setup_apache_once /usr/share/geonode/config-post.sh
         fi
    

# Load back the keywords for kw_bck
    if [ "$(sudo su postgres -c 'psql -d geonode -c "\d maps_layer" ' | awk /kw_bck/'{print $1}')" = 'kw_bck' ]
    then
	cd /var/lib/geonode
	source bin/activate
	python <<EOF
import os
os.environ['DJANGO_SETTINGS_MODULE']='geonode.settings'
from django.db import connection, transaction
from geonode.maps.models import Layer, Map

cursor = connection.cursor()
cursor.execute('SELECT id,kw_bck FROM maps_layer;')
rows = cursor.fetchall()
for row in rows:
	Layer.objects.get(id=row[0]).keywords.add(row[1])
cursor.execute('ALTER TABLE maps_layer DROP kw_bck;')

transaction.commit_unless_managed()
cursor.close()
EOF
    fi
	;;
    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
	echo "postinst called with unknown argument \`$1'" >&2
	exit 1
    ;;
esac

exit 0
